version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gunny
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 123456
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - phpmyadmin_data:/var/www/html

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - ./:/var/www/html/

  php:
    build: .
    expose:
      - 9000
    volumes:
      - ./:/var/www/html/
  
volumes:
  mysql_data:
  phpmyadmin_data: